# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImprovI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImprovI
    pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'
end
